// GENERATED by tools/gen_sample.py — do not edit.
// Пресет по умолчанию для sample-data. Формат — docs/contract.md "Пресет".
window.DS_BASE_PRESET = {
  "name": "base",
  "query": {
    "as_of": null,
    "sources": {
      "CRM": {
        "labels": [
          "customer_id",
          "email",
          "phone",
          "status"
        ]
      },
      "ERP": {
        "labels": [
          "price",
          "stock"
        ]
      }
    }
  },
  "view": {
    "joins": [
      {
        "left": "CRM",
        "left_field": "customer_id",
        "right": "ERP",
        "right_field": "client_ref"
      }
    ],
    "conditions": [],
    "entities": []
  }
};
