// GENERATED by tools/gen_sample.py from real `ds get` output — do not edit.
// Format: docs/contract.md
window.DS = window.DS || { sources: {} };
window.DS.sources["CRM"] = {
  "meta": {
    "name": "CRM",
    "key": "customer_id",
    "as_of": 1706745600.0,
    "generated_at": 1706750000.0,
    "gen_max_cnt": 13,
    "include_archive": false,
    "rows": 4,
    "labels": [
      "email",
      "phone",
      "status"
    ]
  },
  "data": [
    {
      "customer_id": "101",
      "email": "alice@example.com",
      "phone": "+7-900-000-0001",
      "status": "active"
    },
    {
      "customer_id": "102",
      "email": "bob.new@example.com",
      "phone": "+7-900-000-0002",
      "status": "vip"
    },
    {
      "customer_id": "103",
      "email": "carol@example.com",
      "phone": null,
      "status": "active"
    },
    {
      "customer_id": "104",
      "email": "dave@example.com",
      "status": "active"
    }
  ]
};
