// GENERATED by tools/gen_sample.py from real `ds get` output — do not edit.
// Format: docs/contract.md
window.DS = window.DS || { sources: {} };
window.DS.sources["ERP"] = {
  "meta": {
    "name": "ERP",
    "key": "client_ref",
    "as_of": 1706745600.0,
    "generated_at": 1706750000.0,
    "gen_max_cnt": 19,
    "include_archive": false,
    "rows": 3,
    "labels": [
      "price",
      "stock"
    ]
  },
  "data": [
    {
      "client_ref": "101",
      "price": "99.00",
      "stock": "150"
    },
    {
      "client_ref": "102",
      "price": "95.00",
      "stock": null
    },
    {
      "client_ref": "999",
      "price": "10.00",
      "stock": "5"
    }
  ]
};
