#!/usr/bin/env python3
"""Regenerate sample-data/ from real `ds get` output.

This mirrors what the (not-yet-built) poller will do on every refresh:

    ds load <source> <batch> ...      -> DB
    ds get --out <dir> --dt <as_of>   -> pure JSON, one file per source
    wrap each as .js                  -> window.DS.sources[name] = <json>
    build manifest.js                 -> per-source freshness + staleness watermarks

The committed sample deliberately leaves **CRM stale** (one CRM transaction lands
after `ds get`) and **ERP fresh**, so the "regenerate" badge has something to show.

Usage:
    python tools/gen_sample.py          # expects ../ds  (sibling checkout of A1eksMa/ds)
    DS_REPO=/path/to/ds python tools/gen_sample.py
"""
import json
import os
import sqlite3
import subprocess
import sys
import tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
WEBUI = HERE.parent
DS_REPO = Path(os.environ.get("DS_REPO", WEBUI.parent / "ds"))
OUT = WEBUI / "sample-data"

AS_OF = 1706745600            # 2024-02-01; covers every batch below
GENERATED_AT = 1706750000.0  # pinned so the committed sample has a stable diff

if not (DS_REPO / "src" / "cli" / "commands.py").exists():
    sys.exit(f"ds repo not found at {DS_REPO} (set DS_REPO=/path/to/ds)")

work = Path(tempfile.mkdtemp())
db = work / "sample.db"


def ds(*args):
    subprocess.run(
        [sys.executable, "-m", "src.cli.commands", "--db", str(db), *args],
        cwd=str(DS_REPO), check=True,
        env={"PYTHONPATH": str(DS_REPO), "PATH": os.environ.get("PATH", "/usr/bin:/bin")},
    )


def source(name, key_label):
    d = work / name
    d.mkdir(parents=True, exist_ok=True)
    (d / "source.json").write_text(json.dumps({"name": name, "key_label": key_label}))
    return d


_n = [0]


def batch(rows):
    _n[0] += 1
    f = work / f"b{_n[0]}.json"
    f.write_text(json.dumps(rows))
    return f


# --- CRM: POST on 102, DELETE of 103.phone, 104 appears in the 2nd batch --------
crm = source("CRM", "customer_id")
ds("load", str(crm), str(batch({
    "customer_id": ["101", "102", "103"],
    "email": ["alice@example.com", "bob@example.com", "carol@example.com"],
    "phone": ["+7-900-000-0001", "+7-900-000-0002", None],
    "status": ["active", "active", "active"],
})), "--dt", "1704067200")
ds("load", str(crm), str(batch({
    "customer_id": ["102", "104"],
    "email": ["bob.new@example.com", "dave@example.com"],
    "status": ["vip", "active"],
})), "--dt", "1706745600")

# --- ERP: keyed by client_ref; 999 has no CRM match, 102.stock is deleted ------
erp = source("ERP", "client_ref")
ds("load", str(erp), str(batch({
    "client_ref": ["101", "102", "999"],
    "price": ["99.00", "95.00", "10.00"],
    "stock": ["150", None, "5"],
})), "--dt", "1705000000")

# --- the read the poller ships to the browser --------------------------------
gen_dir = work / "out"
ds("get", "--out", str(gen_dir), "--dt", str(AS_OF))

# --- a late CRM transaction: arrives AFTER the read above -> CRM is now stale --
ds("load", str(crm), str(batch({
    "customer_id": ["105"], "email": ["erin@example.com"], "status": ["active"],
})), "--dt", "1706800000")

conn = sqlite3.connect(str(db))


def src_max_cnt(name):
    row = conn.execute(
        "SELECT MAX(cnt) FROM transactions WHERE src = (SELECT src_id FROM srcs WHERE name = ?)",
        (name,),
    ).fetchone()
    return row[0]


db_max_cnt = conn.execute("SELECT MAX(cnt) FROM transactions").fetchone()[0]

OUT.mkdir(parents=True, exist_ok=True)
for stale in OUT.glob("*.js"):
    stale.unlink()

manifest_sources = []
for jf in sorted(gen_dir.glob("*.json")):
    payload = json.loads(jf.read_text())
    name = payload["meta"]["name"]
    payload["meta"]["generated_at"] = GENERATED_AT
    (OUT / f"{name}.js").write_text(
        "// GENERATED by tools/gen_sample.py from real `ds get` output — do not edit.\n"
        "// Format: docs/contract.md\n"
        "window.DS = window.DS || { sources: {} };\n"
        f"window.DS.sources[{json.dumps(name)}] = "
        + json.dumps(payload, ensure_ascii=False, indent=2) + ";\n",
        encoding="utf-8",
    )
    manifest_sources.append({
        "name": name,
        "file": f"{name}.js",
        "key": payload["meta"]["key"],
        "as_of": payload["meta"]["as_of"],
        "generated_at": GENERATED_AT,
        "gen_max_cnt": payload["meta"]["gen_max_cnt"],   # cnt watermark of the shipped file
        "db_max_cnt": src_max_cnt(name),                 # this source's current max in the DB
        "rows": payload["meta"]["rows"],
        "labels": payload["meta"]["labels"],
    })

(OUT / "manifest.js").write_text(
    "// GENERATED by tools/gen_sample.py alongside <Source>.js — do not edit.\n"
    "// In production the poller builds this, not ds core. Compare gen_max_cnt vs\n"
    "// db_max_cnt per source to decide whether a file needs regenerating.\n"
    "window.DS_MANIFEST = "
    + json.dumps({
        "generated_at": GENERATED_AT,
        "db_max_cnt": db_max_cnt,
        "sources": manifest_sources,
    }, ensure_ascii=False, indent=2) + ";\n",
    encoding="utf-8",
)

print("regenerated:", *(p.name for p in sorted(OUT.glob("*.js"))))
for s in manifest_sources:
    tag = "STALE" if s["db_max_cnt"] > s["gen_max_cnt"] else "fresh"
    print(f"  {s['name']:4} gen_max_cnt={s['gen_max_cnt']:3} db_max_cnt={s['db_max_cnt']:3}  [{tag}]")
